// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mvrnormArma
arma::mat mvrnormArma(int n, arma::vec mu, arma::mat sigma);
RcppExport SEXP _mixscat_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_V
arma::mat cpp_compute_V(arma::mat X, arma::vec omega, arma::mat precision_matrix);
RcppExport SEXP _mixscat_cpp_compute_V(SEXP XSEXP, SEXP omegaSEXP, SEXP precision_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision_matrix(precision_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_V(X, omega, precision_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_m
arma::mat cpp_compute_m(arma::mat V, arma::mat X, arma::vec z, arma::vec omega, arma::vec C);
RcppExport SEXP _mixscat_cpp_compute_m(SEXP VSEXP, SEXP XSEXP, SEXP zSEXP, SEXP omegaSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_m(V, X, z, omega, C));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta
arma::mat sample_beta(arma::mat X, arma::vec omega, arma::mat inv_cov, arma::vec z, arma::vec C);
RcppExport SEXP _mixscat_sample_beta(SEXP XSEXP, SEXP omegaSEXP, SEXP inv_covSEXP, SEXP zSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_cov(inv_covSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta(X, omega, inv_cov, z, C));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta2
arma::mat sample_beta2(arma::mat X, arma::vec omega, arma::mat precision_matrix, arma::vec z, arma::vec C);
RcppExport SEXP _mixscat_sample_beta2(SEXP XSEXP, SEXP omegaSEXP, SEXP precision_matrixSEXP, SEXP zSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision_matrix(precision_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta2(X, omega, precision_matrix, z, C));
    return rcpp_result_gen;
END_RCPP
}
// logsumexp_cpp
double logsumexp_cpp(const arma::vec& x);
RcppExport SEXP _mixscat_logsumexp_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_dummy_dense
arma::mat fast_dummy_dense(arma::ivec x, int G);
RcppExport SEXP _mixscat_fast_dummy_dense(SEXP xSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dummy_dense(x, G));
    return rcpp_result_gen;
END_RCPP
}
// sofmax_cpp
arma::mat sofmax_cpp(const arma::mat& x);
RcppExport SEXP _mixscat_sofmax_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sofmax_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// compute_prob_group
arma::mat compute_prob_group(arma::mat& B, arma::mat& beta_group, arma::uvec& idx);
RcppExport SEXP _mixscat_compute_prob_group(SEXP BSEXP, SEXP beta_groupSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta_group(beta_groupSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_prob_group(B, beta_group, idx));
    return rcpp_result_gen;
END_RCPP
}
// predict_prob_cpp
arma::mat predict_prob_cpp(int& M, arma::ivec& w, arma::mat& B, arma::mat& beta);
RcppExport SEXP _mixscat_predict_prob_cpp(SEXP MSEXP, SEXP wSEXP, SEXP BSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_prob_cpp(M, w, B, beta));
    return rcpp_result_gen;
END_RCPP
}
// fast_aggregate_sum
arma::vec fast_aggregate_sum(arma::vec& log_pz, arma::ivec& id);
RcppExport SEXP _mixscat_fast_aggregate_sum(SEXP log_pzSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type log_pz(log_pzSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_aggregate_sum(log_pz, id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixscat_mvrnormArma", (DL_FUNC) &_mixscat_mvrnormArma, 3},
    {"_mixscat_cpp_compute_V", (DL_FUNC) &_mixscat_cpp_compute_V, 3},
    {"_mixscat_cpp_compute_m", (DL_FUNC) &_mixscat_cpp_compute_m, 5},
    {"_mixscat_sample_beta", (DL_FUNC) &_mixscat_sample_beta, 5},
    {"_mixscat_sample_beta2", (DL_FUNC) &_mixscat_sample_beta2, 5},
    {"_mixscat_logsumexp_cpp", (DL_FUNC) &_mixscat_logsumexp_cpp, 1},
    {"_mixscat_fast_dummy_dense", (DL_FUNC) &_mixscat_fast_dummy_dense, 2},
    {"_mixscat_sofmax_cpp", (DL_FUNC) &_mixscat_sofmax_cpp, 1},
    {"_mixscat_compute_prob_group", (DL_FUNC) &_mixscat_compute_prob_group, 3},
    {"_mixscat_predict_prob_cpp", (DL_FUNC) &_mixscat_predict_prob_cpp, 4},
    {"_mixscat_fast_aggregate_sum", (DL_FUNC) &_mixscat_fast_aggregate_sum, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixscat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
