# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_mixscat_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

cpp_eval_ldnorm <- function(x, mu, sigma, z) {
    .Call(`_mixscat_cpp_eval_ldnorm`, x, mu, sigma, z)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_mixscat_mvrnormArma`, n, mu, sigma)
}

cpp_compute_V <- function(X, omega, inv_cov) {
    .Call(`_mixscat_cpp_compute_V`, X, omega, inv_cov)
}

cpp_compute_m <- function(V, X, z, omega, C, center, inv_cov) {
    .Call(`_mixscat_cpp_compute_m`, V, X, z, omega, C, center, inv_cov)
}

sample_alpha <- function(X, omega, inv_cov, z, C, center) {
    .Call(`_mixscat_sample_alpha`, X, omega, inv_cov, z, C, center)
}

logsumexp_cpp <- function(x) {
    .Call(`_mixscat_logsumexp_cpp`, x)
}

