# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_mixscat_mvrnormArma`, n, mu, sigma)
}

cpp_compute_V <- function(X, omega, precision_matrix) {
    .Call(`_mixscat_cpp_compute_V`, X, omega, precision_matrix)
}

cpp_compute_m <- function(V, X, z, omega, C) {
    .Call(`_mixscat_cpp_compute_m`, V, X, z, omega, C)
}

sample_beta <- function(X, omega, inv_cov, z, C) {
    .Call(`_mixscat_sample_beta`, X, omega, inv_cov, z, C)
}

sample_beta2 <- function(X, omega, precision_matrix, z, C) {
    .Call(`_mixscat_sample_beta2`, X, omega, precision_matrix, z, C)
}

logsumexp_cpp <- function(x) {
    .Call(`_mixscat_logsumexp_cpp`, x)
}

fast_dummy_dense <- function(x, G) {
    .Call(`_mixscat_fast_dummy_dense`, x, G)
}

sofmax_cpp <- function(x) {
    .Call(`_mixscat_sofmax_cpp`, x)
}

compute_prob_group <- function(B, beta_group, idx) {
    .Call(`_mixscat_compute_prob_group`, B, beta_group, idx)
}

predict_prob_cpp <- function(M, w, B, beta) {
    .Call(`_mixscat_predict_prob_cpp`, M, w, B, beta)
}

fast_aggregate_sum <- function(log_pz, id) {
    .Call(`_mixscat_fast_aggregate_sum`, log_pz, id)
}

